on: [pull_request, push]
name: Main
jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Current dir
      run: |
          ls
    - name: pycodestyle
      uses: docker://ankitvgupta/pycodestyle
