on: [pull_request]
name: Main
jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pycodestyle
      uses: docker://ankitvgupta/pycodestyle
