on: [pull_request]
Name: Python Style Check
jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pycodestyle
      uses: ankitvgupta/pycodestyle-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
